import numpy as np

n = np.array([1, 2, 3, 4, 5])

print(f"{n =}")
print(f"{np.sin(n) = }")
print(f"{np.cos(n) = }")
print(f"{np.exp(n) = }")
print(f"{np.log(n) = }")
print(f"{np.log10(n) = }")
print(f"{np.log2(n) = }")
print(f"{np.log1p(n) = }")
print(f"{np.sqrt(n) = }") # 开方
print(f"{np.square(n) = }") # 平方
print(f"{np.power(n, 2) = }")
print('-' * 50)
print(f"{np.abs(n) = }")
print(f"{np.absolute(n) = }")
print(f"{np.fabs(n) = }")
print(f"{np.sign(n) = }")
print('-' * 50)
print(f"{np.mod(n, 2) = }")
print(f"{np.modf(n) = }")
print('-' * 50)
print(f"{np.isnan(n) = }")
print(f"{np.isfinite(n) = }")
print(f"{np.isinf(n) = }")
print(f"{np.isposinf(n) = }")
print(f"{np.isneginf(n) = }")
print(f"{np.angle(n) = }")
print(f"{np.real(n) = }")
print(f"{np.imag(n) = }")
print(f"{np.conj(n) = }")
print(f"{np.conjugate(n) = }")
print('-' * 50)


print('np.clip', np.clip(n, 2, 3))
print('np.round', np.round(n))
print('np.floor', np.floor(n))
print('np.ceil', np.ceil(n))
print('np.rint', np.rint(n))
print('np.trunc', np.trunc(n))
# print('np.exponential', np.exponential(n))
# print('np.cube', np.cube(n))
print('np.reciprocal', np.reciprocal(n))